#!/bin/bash
# Setup script for Databricks Asset Bundle configuration
# This script helps you configure workspace URL and authentication
#
# Usage:
#   ./setup_config.sh
#   ./setup_config.sh --workspace-url URL --token TOKEN --username USERNAME
#   DATABRICKS_HOST=URL DATABRICKS_TOKEN=TOKEN ./setup_config.sh

set -e

echo "=========================================="
echo "Databricks Asset Bundle Setup"
echo "=========================================="
echo ""

# Check if databricks CLI is installed
if ! command -v databricks &> /dev/null; then
    echo "❌ Databricks CLI not found. Please install it first:"
    echo "   pip install databricks-cli"
    echo "   or: brew install databricks/tap/databricks"
    exit 1
fi

echo "✅ Databricks CLI found"
echo ""

# Load configuration from .env.local if it exists
if [ -f ".env.local" ]; then
    echo "📁 Loading configuration from .env.local..."
    # Source the file to load variables
    set -a  # Automatically export all variables
    source .env.local
    set +a  # Turn off automatic export
    echo "✅ Configuration loaded from .env.local"
    echo ""
fi

# Parse command line arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        --workspace-url|--host)
            WORKSPACE_URL="$2"
            shift 2
            ;;
        --token)
            DATABRICKS_TOKEN="$2"
            shift 2
            ;;
        --username)
            USERNAME="$2"
            shift 2
            ;;
        *)
            echo "Unknown option: $1"
            echo "Usage: $0 [--workspace-url URL] [--token TOKEN] [--username USERNAME]"
            exit 1
            ;;
    esac
done

# Check environment variables if not provided via command line
# Priority: command line args > .env.local > environment variables > prompt
WORKSPACE_URL="${WORKSPACE_URL:-${DATABRICKS_HOST}}"
DATABRICKS_TOKEN="${DATABRICKS_TOKEN:-${DATABRICKS_TOKEN}}"
USERNAME="${USERNAME:-${DATABRICKS_USERNAME}}"

# Prompt for workspace URL if not provided
if [ -z "$WORKSPACE_URL" ]; then
    read -p "Enter your Databricks workspace URL (e.g., https://workspace.cloud.databricks.com): " WORKSPACE_URL
fi

if [ -z "$WORKSPACE_URL" ]; then
    echo "❌ Workspace URL is required"
    exit 1
fi

# Prompt for token if not provided
if [ -z "$DATABRICKS_TOKEN" ]; then
    read -sp "Enter your Databricks Personal Access Token (hidden): " DATABRICKS_TOKEN
    echo ""
fi

if [ -z "$DATABRICKS_TOKEN" ]; then
    echo "❌ Token is required"
    exit 1
fi

# Configure Databricks CLI
echo ""
echo "Configuring Databricks CLI..."
databricks configure --token <<EOF
$WORKSPACE_URL
$DATABRICKS_TOKEN
EOF

if [ $? -eq 0 ]; then
    echo "✅ Databricks CLI configured successfully"
else
    echo "❌ Failed to configure Databricks CLI"
    exit 1
fi

# Prompt for username if not provided
if [ -z "$USERNAME" ]; then
    echo ""
    read -p "Enter your Databricks username (e.g., your.email@company.com): " USERNAME
fi

if [ -z "$USERNAME" ]; then
    USERNAME="your.email@databricks.com"
fi

WORKSPACE_PATH="/Users/${USERNAME}/demo_ward_clinical_assistant"

# Create/update .env.local file with current values
cat > .env.local <<EOF
# Databricks Configuration
# Generated/updated by setup_config.sh
# This file is gitignored - your credentials will not be committed

DATABRICKS_HOST=$WORKSPACE_URL
DATABRICKS_TOKEN=$DATABRICKS_TOKEN
DATABRICKS_USERNAME=$USERNAME
EOF

# Also create config.local for backward compatibility
cat > config/config.local <<EOF
# Local Configuration (gitignored)
# Generated by setup_config.sh

DATABRICKS_HOST=$WORKSPACE_URL
DATABRICKS_TOKEN=$DATABRICKS_TOKEN
WORKSPACE_PATH=$WORKSPACE_PATH
CATALOG=ward_demo
SCHEMA=justin_ward_demo_ward_clinical_assistant
WAREHOUSE_NAME=Shared Unity Catalog Serverless
PROJECT_NAME=demo_ward_clinical_assistant
EOF

echo "✅ Created .env.local file"
echo "✅ Created config/config.local file"
echo ""
echo "=========================================="
echo "Setup Complete!"
echo "=========================================="
echo ""
echo "Next steps:"
echo "1. Review config/config.local and update WORKSPACE_PATH if needed"
echo "2. Update databricks.yml with your workspace_path if different"
echo "3. Run: databricks bundle validate"
echo "4. Run: databricks bundle deploy"
echo ""

